### ISSUE TITLE
ROVIO limit: artificial imu-timestamp bias

### ISSUE THREAD

**Issue by surberj** [surberj/Vision#15]
Tracking results, Euroc Dataset, IMU-timestamp bias = 0ms, 70ms, 100ms
![screenshot from 2015-11-09 20 23 21](https://cloud.githubusercontent.com/assets/9253897/11044067/135a6724-8720-11e5-9009-30edaddbdd52.png)

ATE_RMSE for biases from 0 to 100 ms
![imu_time](https://cloud.githubusercontent.com/assets/9253897/11044100/34463be8-8720-11e5-8c72-2ab8a260534d.png)

**Comment by devbharat** [comment]
Do you think if it is even possible to have timestamp bais as filter state with no additional measurements ?

**Comment by surberj** [comment]
I was also thinking about that idea... Could be an interesting approach but I doubt that this state would be observable. What do you think?

**Comment by surberj** [comment]
I rather think it needs to be estimated during some intelligent calibration. If there is a constant time sync bias at all --> I do not even know if it is constant, drifting or noisily changing...

**Comment by surberj** [comment]
Results in https://github.com/surberj/Vision/tree/master/thesis/Report
