### ISSUE TITLE
Distortion: Most SFM pipelines / bundle adjustment solvers expect a simplified intrinsics model (f, k1, k2)

### ISSUE THREAD

**Issue by surberj** [surberj/Vision#44]
This means that the principle point is assumed to lie in the center (cx = cy = 0), the focal length is identical in both directions (fx = fy = f) and a simple radial distortion with two params is assumed (x_ = (1 + k1_r^2 + k2_r^4)*x). With this simplifications we introduce errors in the 3d reconstruction (no idea how large they are...).

To get around the issue, I could preprocess and undistort the images. If I do that with my own script using the cv::undistort function I get "clear" quality losses:
original image / undistorted image:
![screenshot from 2016-02-25 13 04 53](https://cloud.githubusercontent.com/assets/9253897/13319220/7815982e-dbc0-11e5-885b-97fe9925e35a.png)

**Comment by devbharat** [comment]
What do you mean quality losses ?

**Comment by surberj** [comment]
Structures are slightly blurred, the ground shows less texture. But probably that is normal?

**Comment by devbharat** [comment]
I can't really see it at this resolution, but no their shouldn't be significant 'blurring'(You should be able to resolve tiny stuff in undistorted image that you did in the original). Of course, it does some sort of interpolation(you can choose, I've always used linear) between pixels, but that shouldn't blur either.

Probably some stuff gets stretched near the edges, so the edges don't seem sharp enough.
