### ISSUE TITLE
Matlab Post Processing

### ISSUE THREAD

**Issue by surberj** [surberj/Vision#6]
General way for post processing in matlab:
- log ros session to .bag file
- convert .bag file to several .csv files (see #8)
- load .csv files with a main script
- do analyses in matlab (position and angle tracking, ...)

Write a routine to read .csv files in matlab.

**Comment by surberj** [comment]
PR: Postprocessing #9

**Comment by devbharat** [comment]
You can also try to load bag files directly in MATLAB if you have the robotics toolbox. See http://ch.mathworks.com/help/robotics/examples/working-with-rosbag-logfiles.html

**Comment by surberj** [comment]
<img width="1212" alt="bildschirmfoto 2015-10-20 um 13 30 52" src="https://cloud.githubusercontent.com/assets/9253897/10605840/e0f42abe-772e-11e5-8c68-663a857ebdf8.png">

**Comment by surberj** [comment]
Decided to go on with python / c++ for analyses, see #14
