### ISSUE TITLE
Frame is newer than oldest IMU measurement.

### ISSUE THREAD

**Issue by maym86** [surberj/Vision#74]
Hi,

I'm getting an error when trying with my own data where the frames aren't processed. It looks like it's to do with the time stamps:

"Frame is newer than oldest IMU measurement. Dropping it."

My cam data 
# timestamp [ns],filename

1467394337801095936,cam0/data/000000000000.jpg
1467394337801126912,cam0/data/000000000001.jpg
1467394337801146880,cam0/data/000000000002.jpg
1467394337801166080,cam0/data/000000000003.jpg
1467394337801186048,cam0/data/000000000004.jpg
1467394337801208064,cam0/data/000000000005.jpg
1467394337801227008,cam0/data/000000000006.jpg
1467394337801244928,cam0/data/000000000007.jpg
1467394337801262080,cam0/data/000000000008.jpg
1467394337801277952,cam0/data/000000000009.jpg
1467394337801295872,cam0/data/000000000010.jpg
1467394337801313024,cam0/data/000000000011.jpg
1467394337801330176,cam0/data/000000000012.jpg
1467394337801346816,cam0/data/000000000013.jpg
1467394337801363968,cam0/data/000000000014.jpg
1467394337801382144,cam0/data/000000000015.jpg
1467394337801406976,cam0/data/000000000016.jpg
1467394337801425152,cam0/data/000000000017.jpg
1467394337801441792,cam0/data/000000000018.jpg
1467394337801457664,cam0/data/000000000019.jpg
1467394337801477120,cam0/data/000000000020.jpg
1467394337801494016,cam0/data/000000000021.jpg
1467394337801511936,cam0/data/000000000022.jpg
1467394337801528832,cam0/data/000000000023.jpg
1467394337801547008,cam0/data/000000000024.jpg
1467394337801563904,cam0/data/000000000025.jpg
1467394337801579776,cam0/data/000000000026.jpg
1467394337801597184,cam0/data/000000000027.jpg
1467394337801614080,cam0/data/000000000028.jpg
1467394337801630976,cam0/data/000000000029.jpg
1467394337801647872,cam0/data/000000000030.jpg
1467394337801666048,cam0/data/000000000031.jpg
1467394337801682944,cam0/data/000000000032.jpg
1467394337801700096,cam0/data/000000000033.jpg
1467394337801716992,cam0/data/000000000034.jpg
1467394337801734912,cam0/data/000000000035.jpg
1467394337801753856,cam0/data/000000000036.jpg
1467394337801771008,cam0/data/000000000037.jpg
1467394337801788160,cam0/data/000000000038.jpg
1467394337801805056,cam0/data/000000000039.jpg
1467394337801822976,cam0/data/000000000040.jpg
1467394337801843968,cam0/data/000000000041.jpg
1467394337801862912,cam0/data/000000000042.jpg
1467394337801882112,cam0/data/000000000043.jpg
1467394337801908992,cam0/data/000000000044.jpg
1467394337801923072,cam0/data/000000000045.jpg
1467394337801942016,cam0/data/000000000046.jpg
1467394337801956864,cam0/data/000000000047.jpg
1467394337801970944,cam0/data/000000000048.jpg
1467394337801985024,cam0/data/000000000049.jpg
1467394337801999104,cam0/data/000000000050.jpg
1467394337802021120,cam0/data/000000000051.jpg
1467394337802035200,cam0/data/000000000052.jpg
1467394337802048768,cam0/data/000000000053.jpg
1467394337802063104,cam0/data/000000000054.jpg
1467394337802077184,cam0/data/000000000055.jpg
1467394337802090752,cam0/data/000000000056.jpg
1467394337802104064,cam0/data/000000000057.jpg
1467394337802117120,cam0/data/000000000058.jpg
1467394337802129920,cam0/data/000000000059.jpg
1467394337802144000,cam0/data/000000000060.jpg
1467394337802158080,cam0/data/000000000061.jpg
1467394337802170880,cam0/data/000000000062.jpg
1467394337802184192,cam0/data/000000000063.jpg
1467394337802198016,cam0/data/000000000064.jpg
1467394337802210816,cam0/data/000000000065.jpg
1467394337802225152,cam0/data/000000000066.jpg
1467394337802237952,cam0/data/000000000067.jpg
1467394337802253056,cam0/data/000000000068.jpg
1467394337802267136,cam0/data/000000000069.jpg
1467394337802279936,cam0/data/000000000070.jpg
1467394337802292992,cam0/data/000000000071.jpg
1467394337802306816,cam0/data/000000000072.jpg
1467394337802320128,cam0/data/000000000073.jpg
1467394337802333952,cam0/data/000000000074.jpg
1467394337802347776,cam0/data/000000000075.jpg
1467394337802365952,cam0/data/000000000076.jpg
1467394337802380032,cam0/data/000000000077.jpg
1467394337802393088,cam0/data/000000000078.jpg
1467394337802405888,cam0/data/000000000079.jpg
1467394337802421248,cam0/data/000000000080.jpg
1467394337802434816,cam0/data/000000000081.jpg
1467394337802447872,cam0/data/000000000082.jpg
1467394337802462208,cam0/data/000000000083.jpg
1467394337802480896,cam0/data/000000000084.jpg
1467394337802495744,cam0/data/000000000085.jpg
1467394337802510080,cam0/data/000000000086.jpg
1467394337802537728,cam0/data/000000000087.jpg
1467394337802552064,cam0/data/000000000088.jpg
1467394337802566144,cam0/data/000000000089.jpg
1467394337802579968,cam0/data/000000000090.jpg
1467394337802594048,cam0/data/000000000091.jpg
1467394337802608896,cam0/data/000000000092.jpg
1467394337802622976,cam0/data/000000000093.jpg
1467394337802637312,cam0/data/000000000094.jpg
1467394337802650880,cam0/data/000000000095.jpg
1467394337802664960,cam0/data/000000000096.jpg
1467394337802679040,cam0/data/000000000097.jpg
1467394337802692864,cam0/data/000000000098.jpg
1467394337802706944,cam0/data/000000000099.jpg
1467394337802725120,cam0/data/000000000100.jpg
1467394337802739968,cam0/data/000000000101.jpg
1467394337802753792,cam0/data/000000000102.jpg
1467394337802769152,cam0/data/000000000103.jpg
1467394337802782976,cam0/data/000000000104.jpg
1467394337802798080,cam0/data/000000000105.jpg
1467394337802817024,cam0/data/000000000106.jpg
1467394337802831872,cam0/data/000000000107.jpg
1467394337802846976,cam0/data/000000000108.jpg
1467394337802861056,cam0/data/000000000109.jpg
1467394337802874880,cam0/data/000000000110.jpg
1467394337802890240,cam0/data/000000000111.jpg
1467394337802903808,cam0/data/000000000112.jpg
...

IMU data:
# timestamp [ns],w_RS_S_x [rad s^-1],w_RS_S_y [rad s^-1],w_RS_S_z [rad s^-1],a_RS_S_x [m s^-2],a_RS_S_y [m s^-2],a_RS_S_z [m s^-2]

1467394337710526976,0.0625,-0.1875,0.0625,0.12,-0.34,9.73
1467394337721240064,0.0,-0.125,0.0,0.1,-0.32,9.78
1467394337730521088,0.0,-0.125,0.0,0.12,-0.33,9.85
1467394337740505856,0.25,-0.0625,0.0,0.12,-0.33,9.87
1467394337750534144,0.1875,0.0625,0.0625,0.11,-0.35,9.87
1467394337760647936,0.0625,-0.25,0.0,0.12,-0.35,9.76
1467394337772721920,-0.125,-0.125,0.0,0.12,-0.34,9.82
1467394337784259072,-0.0625,-0.125,0.0625,0.11,-0.32,9.84
1467394337793925120,0.0625,-0.125,-0.0625,0.14,-0.33,9.86
1467394337804571904,0.0625,-0.0625,0.0,0.13,-0.3,9.88
1467394337814458880,0.0625,0.1875,0.0,0.12,-0.31,9.75
1467394337822580992,0.0,0.125,-0.0625,0.1,-0.33,9.81
1467394337834203904,0.0,0.0,0.0,0.09,-0.33,9.84
1467394337844258048,0.0,-0.125,0.125,0.12,-0.35,9.87
1467394337854265856,0.0625,0.0,-0.0625,0.13,-0.36,9.85
1467394337864464128,0.0,0.0625,0.0,0.15,-0.34,9.74
1467394337873271040,0.0,-0.1875,0.0625,0.13,-0.36,9.79
1467394337884327936,0.0625,0.0625,-0.0625,0.12,-0.33,9.84
1467394337893198848,0.0625,-0.0625,-0.125,0.13,-0.3,9.88
1467394337904128256,0.125,0.125,0.0625,0.11,-0.31,9.87
1467394337912763136,0.0625,-0.0625,0.0,0.11,-0.31,9.75
1467394337922630144,0.0625,-0.125,0.0625,0.11,-0.33,9.83
1467394337933895936,0.0625,-0.0625,0.0625,0.1,-0.33,9.84
1467394337944329984,-0.0625,0.0625,0.1875,0.12,-0.36,9.87
1467394337954157312,-0.0625,0.0,0.0,0.16,-0.36,9.89
1467394337964092928,0.0625,0.125,0.0,0.13,-0.37,9.73
1467394337973289984,0.0,0.125,-0.0625,0.11,-0.34,9.79
1467394337983196928,-0.0625,0.0625,0.0625,0.08,-0.33,9.84
1467394337994126080,-0.0625,0.0,-0.0625,0.1,-0.29,9.82
1467394338003032832,-0.0625,0.1875,-0.0625,0.12,-0.28,9.82
1467394338012717056,-0.0625,0.0,0.125,0.14,-0.3,9.76
1467394338022685952,-0.125,0.0,0.0,0.14,-0.32,9.77
1467394338033746944,-0.0625,0.125,0.0625,0.17,-0.32,9.81
1467394338042635008,0.0,0.0,0.125,0.09,-0.37,9.93
1467394338052697088,0.0625,0.0625,-0.0625,0.14,-0.4,9.86
1467394338062654976,-0.125,0.0,0.0,0.09,-0.38,9.72
1467394338072656128,-0.0625,0.1875,-0.125,0.11,-0.34,9.81
1467394338082642944,0.0,-0.125,0.0625,0.11,-0.31,9.85
1467394338092649984,0.125,-0.0625,0.0,0.16,-0.3,9.84
1467394338102653952,-0.125,-0.1875,0.0,0.23,-0.28,9.88
1467394338112659968,-0.0625,0.0625,0.0625,0.1,-0.34,9.75
1467394338122669056,0.0625,0.1875,0.0625,0.05,-0.34,9.82
1467394338132715776,0.0625,0.0625,0.0625,0.05,-0.35,9.86
1467394338142710016,0.0,0.0,0.0625,0.06,-0.35,9.86
1467394338152731904,-0.125,-0.0625,0.125,0.15,-0.34,9.8
1467394338162674688,0.0,0.0625,0.125,0.14,-0.35,9.73
1467394338172715776,0.0,0.0625,0.125,0.16,-0.33,9.78
1467394338182624000,0.0,0.0,0.0,0.15,-0.32,9.84
1467394338192658944,0.0,0.0,0.0,0.15,-0.34,9.89
1467394338202681088,0.0,0.125,0.0,0.1,-0.36,9.87
1467394338212658944,0.0,0.0,0.125,0.1,-0.35,9.74
1467394338222642944,0.125,0.0625,0.0,0.07,-0.34,9.81
1467394338232637952,0.0,0.0625,0.0,0.1,-0.32,9.83
1467394338242633984,0.0,0.0,0.0,0.09,-0.3,9.86
1467394338252603904,-0.0625,-0.0625,0.0,0.13,-0.31,9.9
1467394338262559744,0.0,-0.1875,0.0,0.13,-0.33,9.72
1467394338272571136,0.0,0.1875,0.0,0.14,-0.35,9.82
1467394338283204096,0.125,0.1875,0.0625,0.09,-0.34,9.87
1467394338292582912,0.0,0.0,-0.0625,0.09,-0.36,9.85
1467394338302606080,-0.0625,-0.125,0.0,0.1,-0.36,9.83
1467394338312642048,0.0625,0.125,0.0,0.13,-0.34,9.73
1467394338322671872,0.0,-0.125,0.0625,0.14,-0.32,9.79
1467394338332698112,0.125,0.0,0.0625,0.12,-0.32,9.83
1467394338342675968,0.0625,0.125,0.0,0.12,-0.32,9.88
1467394338352663040,-0.1875,0.125,0.125,0.15,-0.32,9.87
1467394338362678016,-0.0625,0.0625,0.0,0.13,-0.32,9.73
1467394338372685824,0.0625,0.0,-0.0625,0.12,-0.35,9.86
1467394338382669056,0.0,0.1875,-0.0625,0.11,-0.35,9.83
1467394338392695808,0.0,0.0,0.0,0.1,-0.36,9.89
1467394338402665984,-0.125,-0.0625,0.0,0.13,-0.36,9.89
1467394338412695808,0.0625,-0.0625,0.0,0.13,-0.34,9.76

**Comment by maym86** [comment]
Sorry wrong repo

**Comment by surberj** [comment]
no problem :)
